{% set version = "0.36.0" %}
{% set name = "azure-storage" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb6212dcbed91b49d9637aa5e8888eafdfcd523b7e560c8044d2d838bbd3ca5f

build:
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  number: 1000

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - azure-common >=1.1.5
    - python-dateutil
    - requests
    - futures  # [py2k]

test:
  requires:
    - vcrpy
  imports:
    - azure
    - azure.storage
    - azure.storage._http
    - azure.storage.blob
    - azure.storage.file
    - azure.storage.queue
    - azure.storage.table
  commands:
    - python -m unittest discover -p "test_*.py"

about:
  home: https://github.com/Azure/azure-storage-python
  license: Apache-2.0
  summary: 'Microsoft Azure Storage Client Library for Python'

extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
